=== rv1971/alcamo-dom/tests/foo.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE xsd:schema [
<!ATTLIST xsd:complexType id ID #IMPLIED>
<!ATTLIST xsd:element     id ID #IMPLIED>
]>

<xsd:schema
    xmlns="http://foo.example.org"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:owl="http://www.w3.org/2002/07/owl#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:xh11d="http://www.w3.org/1999/xhtml/datatypes/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:foo2="http://foo2.example.org"
    dc:identifier="FOO"
    targetNamespace="http://foo.example.org"
    elementFormDefault="qualified">

  <xsd:import
      namespace="http://www.w3.org/2000/01/rdf-schema#"
      schemaLocation="../xsd/rdfs.xsd"/>

  <xsd:import
      namespace="http://purl.org/dc/terms/"
      schemaLocation="../xsd/dc.xsd"/>

  <xsd:import
      namespace="http://www.w3.org/2002/07/owl#"
      schemaLocation="../xsd/owl.xsd"/>

  <xsd:import
      namespace="http://www.w3.org/XML/1998/namespace"
      schemaLocation="../xsd/xml.xsd"/>

  <xsd:import
      namespace="http://www.w3.org/1999/xhtml/datatypes/"
      schemaLocation="../xsd/xhtml-datatypes-1.xsd"/>

  <xsd:import
      xmlns="http://foo2.example.org"
      schemaLocation="foo2.xsd"/>

  <xsd:attribute name="quux" type="xsd:short"/>

  <xsd:element
      name="foo"
      id="foo"
      rdfs:label="language-agnostic foo"
      rdfs:comment="language-agnostic description">
    <xsd:annotation>
      <xsd:appinfo xml:lang="es">
        <rdfs:comment xml:lang="en">Description</rdfs:comment>
        <rdfs:comment>Descripción</rdfs:comment>
      </xsd:appinfo>

      <xsd:appinfo xml:lang="fr">
        <rdfs:label xml:lang="en">English foo</rdfs:label>
        <rdfs:label xml:lang="de">deutsches foo</rdfs:label>
        <rdfs:label>foo français</rdfs:label>
      </xsd:appinfo>
    </xsd:annotation>

    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="rdfs:comment"/>

        <xsd:element name="bar" id="bar" type="AbstractBar">
          <xsd:annotation>
            <xsd:appinfo>
              <rdfs:label xml:lang="it">bar italiano</rdfs:label>
              <rdfs:label xml:lang="en">English bar</rdfs:label>
            </xsd:appinfo>

            <xsd:appinfo xml:lang="it">
              <rdfs:comment>Descrizione</rdfs:comment>
              <rdfs:comment xml:lang="de">Beschreibung</rdfs:comment>
            </xsd:appinfo>
          </xsd:annotation>
        </xsd:element>

        <xsd:element name="corge">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element ref="rdfs:label"/>
            </xsd:sequence>

            <xsd:attribute ref="xml:id"/>
            <xsd:attribute ref="rdfs:label"/>
            <xsd:attribute name="datetime" type="xsd:date"/>
            <xsd:attribute name="safecurie" type="xh11d:SafeCURIE"/>

            <xsd:attribute name="list">
              <xsd:simpleType>
                <xsd:list itemType="xsd:string"/>
              </xsd:simpleType>
            </xsd:attribute>

            <xsd:attribute name="shorts">
              <xsd:simpleType>
                <xsd:list itemType="xsd:short"/>
              </xsd:simpleType>
            </xsd:attribute>

            <xsd:attribute name="enum" type="xsd:typeDerivationControl"/>

            <xsd:attribute name="enums">
              <xsd:simpleType>
                <xsd:list itemType="xsd:typeDerivationControl"/>
              </xsd:simpleType>
            </xsd:attribute>
          </xsd:complexType>
        </xsd:element>

        <xsd:element ref="xsd:annotation"/>

        <xsd:element ref="qux"/>
      </xsd:sequence>

      <xsd:attribute ref="xml:lang"/>
      <xsd:attribute ref="dc:source"/>
      <xsd:attribute ref="quux"/>
      <xsd:attribute name="qux"/>
      <xsd:attribute name="bar" type="xsd:boolean"/>
      <xsd:attribute name="baz" type="xsd:boolean"/>
      <xsd:attribute name="foobar"/>
      <xsd:attribute name="barbaz" type="xsd:long"/>
      <xsd:attribute name="bazbaz"/>

      <xsd:attribute name="foofoofoo">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string"/>
        </xsd:simpleType>
      </xsd:attribute>

      <xsd:attribute name="barbarbar">
        <xsd:simpleType>
          <xsd:list itemType="xsd:token"/>
        </xsd:simpleType>
      </xsd:attribute>

      <xsd:attribute name="bazbazbaz">
        <xsd:simpleType>
          <xsd:restriction base="foo2:DerivedFromList"/>
        </xsd:simpleType>
      </xsd:attribute>

      <xsd:anyAttribute namespace="##any" processContents="lax"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="quux" type="xsd:duration"/>

  <xsd:complexType name="QuuxContainer">
    <xsd:sequence>
      <xsd:element ref="quux"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:element name="anyQuux"/>

  <xsd:element name="corge1">
    <xsd:simpleType>
      <xsd:restriction base="xsd:language"/>
    </xsd:simpleType>
  </xsd:element>

  <xsd:element name="corge2">
    <xsd:simpleType>
      <xsd:restriction base="xsd:NMTOKENS"/>
    </xsd:simpleType>
  </xsd:element>

  <xsd:complexType name="AbstractBar" abstract="true"/>

  <xsd:complexType name="Bar" id="Bar">
    <xsd:complexContent>
      <xsd:extension base="AbstractBar">
        <xsd:sequence>
          <xsd:element name="baz" maxOccurs="unbounded">
            <xsd:complexType>
              <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                  <xsd:attribute ref="xml:base"/>
                  <xsd:attribute ref="xml:id"/>
                  <xsd:attribute ref="rdfs:label"/>
                  <xsd:attribute ref="owl:sameAs"/>
                  <xsd:attribute name="content"/>
                </xsd:extension>
              </xsd:simpleContent>
            </xsd:complexType>
          </xsd:element>

          <xsd:element ref="rdfs:label" maxOccurs="unbounded"/>
        </xsd:sequence>

        <xsd:attribute ref="xml:id"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="Baz">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute ref="xml:lang"/>
        <xsd:attribute name="baz"/>
        <xsd:attributeGroup ref="xsd:occurs"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="Qux">
    <xsd:simpleContent>
      <xsd:restriction base="Baz">
        <xsd:attribute ref="xml:lang"/>
        <xsd:attribute name="baz"/>
        <xsd:attributeGroup ref="xsd:occurs"/>
      </xsd:restriction>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="fooComplexType">
    <xsd:complexContent>
      <xsd:restriction base="xsd:localComplexType"/>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:element name="qux" type="xsd:short"/>

  <xsd:simpleType name="numericUnion">
    <xsd:union memberTypes="xsd:byte xsd:unsignedShort">
      <xsd:simpleType>
        <xsd:restriction base="xsd:unsignedInt"/>
      </xsd:simpleType>
    </xsd:union>
  </xsd:simpleType>
</xsd:schema>

=== rv1971/alcamo-dom/tests/converter-data.xml
<?xml version="1.0"?>

<foo
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:qux="http://qux.example.org"
    xsi:schemaLocation="http://foo.example.org foo.xsd http://www.w3.org/1999/xhtml/datatypes/ ../xsd/xhtml-datatypes-1.xsd">
  <bar xml:id="base64ToBinary" value="Zm9vCg=="/>
  <bar xml:id="curieToUri" value="dc:source"/>
  <bar xml:id="hexToBinary" value="1234abcdef"/>
  <bar xml:id="pairsToMap" value="foo bar baz-qux 42"/>
  <bar xml:id="resolveIdRef" value="toLang"/>
  <bar xml:id="safeCurieToUri" value="[qux:#1234]"/>
  <bar xml:id="toArray" value="foo   bar	baz"/>
  <bar xml:id="toBool.1" value="true"/>
  <bar xml:id="toBool.2" value="false"/>
  <bar xml:id="toDateTime" value="2021-02-16T18:04:03.123+00:00"/>
  <bar xml:id="toDocument" value="foo.xml"/>
  <bar xml:id="toDocumentOrElement" value="foo.xml#bar"/>
  <bar xml:id="toDuration" value="PT5M"/>
  <bar xml:id="toFloat" value="3.141"/>
  <bar xml:id="toInt" value="42"/>
  <bar xml:id="toIntSet" value="42 -42 0 7 5"/>
  <bar xml:id="toLang" value="yo-NG"/>
  <bar xml:id="toLiteral.1" value="Lorem ipsum"/>
  <bar xml:id="toLiteral.2" xml:lang="it" value="libertÃ "/>
  <bar
      xmlns="http://www.w3.org/1999/xhtml"
      xml:id="toLiteral.3"
      datatype="http://www.w3.org/2001/XMLSchema#date"
      value="2026-01-30"/>
  <bar
      xmlns="http://www.w3.org/1999/xhtml"
      xml:id="toLiteral.4"
      datatype="http://www.w3.org/2001/XMLSchema#boolean">true</bar>
  <bar xml:id="toMediaType" value="application/json"/>
  <bar xml:id="toNonNegativeRange" value="42-43"/>
  <bar xml:id="toSet" value="foo&#x0d;bar&#x0a;baz"/>
  <bar xml:id="toUri" value="http://www.example.org/foo"/>
  <bar xml:id="toXName" value="dc:title"/>
  <bar xml:id="uriOrSafeCurieToUri.1" value="http://www.example.biz/foo"/>
  <bar xml:id="uriOrSafeCurieToUri.2" value="[xsd:#token]"/>
  <bar xml:id="xhRelToUri" value="icon"/>
  <bar xml:id="xPointerUriToSubset" value="bar.xml#appinfo2"/>
  <baz
      xml:id="xPointerUriToValueSet"
      value="#xpointer(//@xml:id[starts-with^(., 'toD'^)])"/>
  <bar xml:id="yesNoToBool.1" value="yes"/>
  <bar xml:id="yesNoToBool.2" value="no"/>
  <bar xml:id="toRdfaDatatype.1" value="true"/>
  <bar
      xmlns="http://www.w3.org/1999/xhtml"
      xml:id="toRdfaDatatype.2"
      datatype="xsd:boolean"
      value="true"/>
  <bar
      xmlns="http://www.w3.org/1999/xhtml"
      xml:id="toRdfaDatatype.3"
      datatype="xsd:formChoice"
      value="qualified"
      prefix="**"/>
  <bar
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:foo-xsd="foo.xsd#"
      xml:id="toRdfaDatatype.4"
      datatype="foo-xsd:UpperString"
      value="Lorem ipsum."/>
  <bar
      xmlns="http://www.w3.org/1999/xhtml"
      xml:id="toRdfaDatatype.5"
      datatype="xsd:reducedDerivationControl"
      value="restriction"/>
  <bar
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:foo-xsd="foo.xsd#"
      xml:id="toRdfaDatatype.6"
      datatype="foo-xsd:SimpleList"
      value="foo bar baz"/>
  <bar
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:foo-xsd="foo.xsd#"
      xml:id="toRdfaDatatype.7"
      datatype="foo-xsd:ListOfEnum"
      value="BAZ BAR FOO"/>
  <bar
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:bar="https://bar.example.com"
      xmlns:foo-xsd="foo.xsd#"
      xmlns:rel="rel#"
      xml:id="toRdfaDatatype.8"
      datatype="foo-xsd:Curies"
      value="bar:#top rel:item"/>
  <bar
      xmlns="http://www.w3.org/1999/xhtml"
      xml:id="toRdfaDatatype-invalid"
      datatype="xsd:foo"
      value="bar"/>
</foo>
